In [20]:
import pandas as pd
from app.common.holder import *
from app.common.preprocess import *
import matplotlib_inline

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
df_company, df_founder_legal, df_founder_natural = get_dfs()

display(df_founder_legal.head(20))

,id,company_id,ogrn,inn,full_name,share,share_percent,owner_id
0,1,6,1037401354671,7423019252,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АКРО...",44454000.0,NaN,<NA>
1,2,8,1021602841402,1654017170,МИНИСТЕРСТВО ЗДРАВООХРАНЕНИЯ РЕСПУБЛИКИ ТАТАРСТАН,0.0,NaN,70865
2,3,25,1081682003358,1639039451,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""МОДУЛЬ""",1088974.0,0.2,<NA>
3,4,36,1030100507370,0101000469,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",0.0,NaN,<NA>
4,5,40,1030100507370,0101004690,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",0.0,NaN,<NA>
5,6,55,1030100507370,0101004690,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",0.0,NaN,<NA>
6,7,60,1060105018467,0105050658,УПРАВЛЕНИЕ ГОСУДАРСТВЕННОЙ СЛУЖБЫ ЗАНЯТОСТИ НА...,NaN,NaN,<NA>
7,8,63,1030100507601,0103007791,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""КОШЕ...",NaN,NaN,<NA>
8,9,74,1030100507370,0101004690,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",NaN,NaN,<NA>
9,10,92,1030100508888,0101004820,УПРАВЛЕНИЕ КУЛЬТУРЫ АДМИНИСТРАЦИИ МУНИЦИПАЛЬН...,NaN,NaN,<NA>
10,11,96,1020100700509,0105017210,МИНИСТЕРСТВО ОБРАЗОВАНИЯ И НАУКИ РЕСПУБЛИКИ АД...,0.0,NaN,<NA>
11,12,96,1020100700509,0105017210,МИНИСТЕРСТВО ОБРАЗОВАНИЯ И НАУКИ РЕСПУБЛИКИ АД...,0.0,NaN,<NA>
12,13,100,1030100507601,0103007791,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""КОШЕ...",0.0,NaN,<NA>
13,14,107,1030100507601,0103007791,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""КОШЕ...",0.0,NaN,<NA>
14,15,113,1030100507601,0103007791,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""КОШЕ...",0.0,NaN,<NA>
15,16,121,1020100703402,0105023407,МИНИСТЕРСТВО ТРУДА И СОЦИАЛЬНОГО РАЗВИТИЯ РА,0.0,NaN,<NA>
16,17,124,1020100509660,0103006558,АДМИНИСТРАЦИЯ КОШЕХАБЛЬСКОГО РАЙОНА,0.0,NaN,<NA>
17,18,126,1030100507370,0101004690,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",0.0,NaN,<NA>
18,19,127,1030100507601,0103007791,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""КОШЕ...",0.0,NaN,<NA>
19,20,129,1030100507370,0101004690,"АДМИНИСТРАЦИЯ МУНИЦИПАЛЬНОГО ОБРАЗОВАНИЯ ""ГИАГ...",NaN,NaN,<NA>

In [15]:
# Группируем по ФИО и подсчитываем количество уникальных 'inn'
fio_inn_counts = df_founder_natural.groupby(
    ['last_name', 'first_name', 'second_name']
)['inn'].nunique().reset_index(name='unique_inn_count')

# Вывод промежуточного результата
print("\nКоличество уникальных 'inn' для каждого ФИО:")
print(fio_inn_counts)

Количество уникальных 'inn' для каждого ФИО:
         last_name first_name      second_name  unique_inn_count
0         АБАКАРОВ     РУСЛАН          ДИМОВИЧ              1034
1           АБАСОВ     КАМИЛЬ     ГАБДУЛХАЕВИЧ               553
2    АБДУЛГАДЖИЕВА    ПАТИМАТ      МАГОМЕДОВНА               308
3    АБДУРАХМАНОВА      АЙШАТ       АБАКАРОВНА               625
4       АБУЛАЙСОВА      АСИЯТ       САРАБИЕВНА               291
..             ...        ...              ...               ...
298        ЯРМЕЕВА      КЛАРА     АХМЕТХАНОВНА               146
299    ЯРМУХАМЕТОВ      АНВАР  МУХАМАТГАРИЕВИЧ                72
300         ЯРОВОЙ      РОМАН       ЕВГЕНЬЕВИЧ               426
301        ЯРУЛЛИН      ЛЕНАР       ФАИМЯНОВИЧ                57
302           ЯХИН      РАДИК        РАИЛЬЕВИЧ               387

[303 rows x 4 columns]

In [ ]:
# Находим индекс строки с максимальным количеством уникальных 'inn'
max_idx = fio_inn_counts['unique_inn_count'].idxmax()

# Извлекаем соответствующее ФИО и количество
top_fio = fio_inn_counts.loc[max_idx]

print("\nФИО с наибольшим количеством уникальных 'inn':")
print(f"Фамилия: {top_fio['last_name']}, Имя: {top_fio['first_name']}, Отчество: {top_fio['second_name']}, Количество уникальных 'inn': {top_fio['unique_inn_count']}")

ФИО с наибольшим количеством уникальных 'inn':
Фамилия: АСТАНИН, Имя: АЛЕКСАНДР, Отчество: ИВАНОВИЧ, Количество уникальных 'inn': 5327

In [19]:
df_people = pd.read_table(
    'app\\data\\processed\\founder_natural.tsv',
    header=0,
    dtype={
        'id': 'Int64',
        'ogrn': 'string',
        'inn': 'string',
        'full_name': 'string'
    },
    na_values=['', ' ', 'NA', 'nan']
)

EmptyDataError: No columns to parse from file

In [ ]:
company_df = pd.read_csv("app/data/processed/company.tsv", sep="\t")

,id,ogrn,inn,full_name
0,42671,1021000861144,1003405007,"МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""..."
1,53821,1021300661910,1308078876,ОТДЕЛ МИНИСТЕРСТВА ВНУТРЕННИХ ДЕЛ РОССИЙСКОЙ Ф...
2,26724,1020500991818,515011966,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЮС С..."
3,2394,1020200784603,220005621,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ФИРМА...
4,65386,1021601373474,1639018758,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ТОРГО...
...,...,...,...,...
99605,22019,1020300986298,326009760,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""СИНЕМА"""
99606,25009,1020400768035,411059843,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ПОСТ..."
99607,95830,1022001545554,2004000693,"КРЕСТЬЯНСКО-ФЕРМЕРСКОЕ ХОЗЯЙСТВО ""ИЛЛИ"""
99608,82077,1021607358145,1634002955,ГОСУДАРСТВЕННОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ...
99609,13146,1020202394740,273034471,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ГОЛД..."

In [16]:
founder_legal_df = pd.read_csv("app/data/processed/founder_legal.tsv", sep="\t")
len(founder_legal_df)

17654

In [17]:
founder_natural_df = pd.read_csv("app/data/processed/founder_natural.tsv", sep="\t")
len(founder_natural_df)

125151

,id,ogrn,inn,full_name
0,42671,1021000861144,1003405007,"МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""..."
1,53821,1021300661910,1308078876,ОТДЕЛ МИНИСТЕРСТВА ВНУТРЕННИХ ДЕЛ РОССИЙСКОЙ Ф...
2,26724,1020500991818,0515011966,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЮС С..."
3,2394,1020200784603,0220005621,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ФИРМА...
4,65386,1021601373474,1639018758,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ТОРГО...
...,...,...,...,...
99604,22019,1020300986298,0326009760,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""СИНЕМА"""
99605,25009,1020400768035,0411059843,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ПОСТ..."
99606,95830,1022001545554,2004000693,"КРЕСТЬЯНСКО-ФЕРМЕРСКОЕ ХОЗЯЙСТВО ""ИЛЛИ"""
99607,82077,1021607358145,1634002955,ГОСУДАРСТВЕННОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ...
99608,13146,1020202394740,0273034471,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ГОЛД..."

In [ ]:
for company in df_company:
    print(0)